version: '3.8'

services:
  app:
    build: .
    container_name: sentinel-app-1
    ports:
      - "5000:5000"
    networks:
      - sentinel-net
    restart: always

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonar-sonarqube-1
    ports:
      - "9005:9000"
    networks:
      - sentinel-net
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    restart: always

prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - sentinel-net
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - sentinel-net
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - sentinel-net
    restart: always

 loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /home/ubuntu/loki-config/loki-local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - sentinel-net
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/sonar/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - sentinel-net
    restart: always

grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - sentinel-net
    restart: always

networks:
  sentinel-net:
    driver: bridge

volumes:
  sonarqube-data:
  grafana-data:
